parameters:
    # directory in storyblok where pages are stored
    storyblok.page-directory: 'pages/'
    # default routing prefix for storyblok pages
    storyblok.base-route: '/storyblok'
    storyblok.assets_downloader.local_storage: '%shopware.filesystem.public.config.root%/cms-pictures/'
    storyblok.assets_downloader.public_path: '/cms-pictures/'

    storyblok.api-keys:
        preview: ''    # test preview
        public: ''    # test public

    storyblok.json-dumper:
#        write: false
#        read: false
        dump-path: '%kernel.cache_dir%/cms/json'


services:
    # route loader
    #  cms.storyblok_route_loader:
    #    class: 'Efrogg\Bundle\StoryblokBundle\Routing\RouteLoader'
    #    calls:
    #      - ['setBaseRoute',['%storyblok.base-route%']]
    #      - ['setPageDirectory',['%storyblok.page-directory%']]
    #    tags:
    #    - 'routing.route_loader'

    # node provider
    cms.storyblok_node_provider:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\NodeProvider\StoryBlokNodeProvider'
        arguments:
            - '%storyblok.api-keys%'
            - '@cms.logger'
        calls:
            - ['setCache',['@cms.cache.json']]
        tags:
            - 'cms.node_provider'
            - 'cms.cache_clear.on_unpublish'

    cms.storyblok_node_provider_json:
        class: Efrogg\ContentRenderer\NodeProvider\SimpleJsonFileNodeProvider
        arguments:
            - "@=container.getParameter('storyblok.json-dumper')['dump-path']"
        calls:
            - ['setLogger',['@cms.logger']]

    # assets
    cms.storyblok.asset_handler:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\Asset\StoryBlokAssetHandler'
        tags:
            - { name: 'cms.asset_handler',key: 1 }

    cms.storyblok_asset_handler_downloader:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\Asset\AssetDownloader'
        arguments:
            - '%storyblok.assets_downloader.local_storage%'
            - '%storyblok.assets_downloader.public_path%'
        calls:
            - ['setLogger',['@cms.logger']]
            - ['setAssetHandler',['@cms.storyblok.asset_handler']]

    cms.storyblok.cache:
        class: 'Efrogg\ContentRenderer\Cache\VarExporterCache'
        arguments:
            - '%cms.cache.storage-path%'
            - '@cms.event_dispatcher'
            - '@cms.logger'


    Efrogg\Bundle\StoryblokBundle\Controller\StoryblokController:
        arguments:
            - '@cms.renderer'
            - '%storyblok.page-directory%'

        calls:
            - [ 'setContainer',[ '@service_container' ] ]
        tags:
            - 'controller.service_arguments'

