parameters:
    # directory in storyblok where pages are stored
    storyblok.page-directory: 'pages/'
    # default routing prefix for storyblok pages
    storyblok.base-route: '/storyblok'
    storyblok.assets_downloader.local_storage: '%shopware.filesystem.public.config.root%/cms-pictures/'
    storyblok.assets_downloader.public_path: '/cms-pictures/'
    storyblok.assets_downloader.use: false
    storyblok.max_retries: 3
    storyblok.api-keys:
        preview: ''    # test preview
        public: ''    # test public

    storyblok.json-dumper.dump-path: '%kernel.cache_dir%/cms/json'
    # low priority to be used as fallback
    storyblok.json-dumper.use: false


services:
    # route loader
    #  cms.storyblok_route_loader:
    #    class: 'Efrogg\Bundle\StoryblokBundle\Routing\RouteLoader'
    #    calls:
    #      - ['setBaseRoute',['%storyblok.base-route%']]
    #      - ['setPageDirectory',['%storyblok.page-directory%']]
    #    tags:
    #    - 'routing.route_loader'

    # node provider
    cms.storyblok_node_provider:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\NodeProvider\StoryBlokNodeProvider'
        arguments:
            - '%storyblok.api-keys%'
            - '@cms.logger'
        calls:
            - ['setCache',['@cms.cache.json']]
            - ['setMaxRetries',['%storyblok.max_retries%']]
        tags:
            - 'cms.node_provider'
            - 'cms.cache_clear.on_unpublish'

    cms.storyblok_node_provider_json_fallback:
        class: Efrogg\ContentRenderer\NodeProvider\SimpleJsonFileNodeProvider
        arguments:
            - "%storyblok.json-dumper.dump-path%"
        calls:
            - ['setLogger',['@cms.logger']]
        # tag and priority are defined at CompilerPass
        # depending on parameter "storyblok.json-dumper.use"

    # assets
    # tag will be set to one handler only at CompilerPass
    # depending on parameter "storyblok.assets_downloader.use"
    cms.storyblok.asset_handler:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\Asset\StoryBlokAssetHandler'

    cms.storyblok.cached_asset_handler:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\Asset\AssetDownloader'
        arguments:
            - '%storyblok.assets_downloader.local_storage%'
            - '%storyblok.assets_downloader.public_path%'
        calls:
            - ['setLogger',['@cms.logger']]
            - ['setAssetHandler',['@cms.storyblok.asset_handler']]

    cms.storyblok.cache:
        class: 'Efrogg\ContentRenderer\Cache\VarExporterCache'
        arguments:
            - '%cms.cache.storage-path%'
            - '@cms.event_dispatcher'
            - '@cms.logger'


    Efrogg\Bundle\StoryblokBundle\Controller\StoryblokController:
        arguments:
            - '@cms.renderer'
            - '%storyblok.page-directory%'

        calls:
            - [ 'setContainer',[ '@service_container' ] ]
        tags:
            - 'controller.service_arguments'

