parameters:
    env(STORYBLOK_DEMO_TOKEN): 'demo-token'

services:
    # route loader
    #  cms.storyblok_route_loader:
    #    class: 'Efrogg\Bundle\StoryblokBundle\Routing\RouteLoader'
    #    calls:
    #      - ['setBaseRoute',['@storyblok.config.getBaseRoute()']]
    #      - ['setPageDirectory',['@storyblok.config.getPagesDirectory()']]
    #    tags:
    #    - 'routing.route_loader'

    storyblok.config:
        class: Efrogg\Bundle\StoryblokBundle\DependencyInjection\StoryblokConfig
        public: true

    # node provider
    cms.storyblok_node_provider:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\NodeProvider\StoryBlokNodeProvider'
        arguments:
            $apiKeys: '@=service("storyblok.config").getApiKeys()'
            $eventDispatcher: '@event_dispatcher'
            $logger: '@cms.logger'
        calls:
            - ['setCache',['@cms.cache.json']]
            - ['setMaxRetries',['@=service("storyblok.config").getApiMaxRetries()']]
        tags:
            - 'cms.node_provider'
            - 'cms.cache_clear.on_unpublish'

    cms.storyblok_node_provider_json_fallback:
        class: Efrogg\ContentRenderer\NodeProvider\SimpleJsonFileNodeProvider
        arguments:
            $rootPath: '@=service("storyblok.config").getJsonDumperPath()'
        calls:
            - ['setLogger',['@cms.logger']]
        # tag and priority are defined at CompilerPass
        # depending on parameter "storyblok.json-dumper.use"

    # assets
    # tag will be set to one handler only at CompilerPass
    # depending on parameter "storyblok.assets_downloader.use"
    cms.storyblok.asset_handler:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\Asset\StoryBlokAssetHandler'

    cms.storyblok.cached_asset_handler:
        class: 'Efrogg\ContentRenderer\Connector\Storyblok\Asset\AssetDownloader'
        arguments:
            $baseStoragePath: '@=service("storyblok.config").getAssetsLocalStorage()'
            $basePublicPath: '@=service("storyblok.config").getAssetsPublicPath()'
        calls:
            - ['setLogger',['@cms.logger']]
            - ['setAssetHandler',['@cms.storyblok.asset_handler']]

    cms.storyblok.cache:
        class: 'Efrogg\ContentRenderer\Cache\VarExporterCache'
        arguments:
            - '%cms.cache.storage-path%'
            - '@cms.event_dispatcher'
            - '@cms.logger'

    Efrogg\Bundle\StoryblokBundle\Controller\StoryblokController:
        arguments:
            $cmsRenderer: '@cms.renderer'
            $pagePath: '@=service("storyblok.config").getPagesDirectory()'
        calls:
            - [ 'setContainer',[ '@service_container' ] ]
        tags:
            - 'controller.service_arguments'

