storyblok:
    pages:
        directory:
            - 'pages/'
        base_route: '/storyblok'
    assets:
        downloader:
            use: false
            local_storage: '%storyblok_storage_root%/cms-pictures/'
            public_path: '/cms-pictures/'
    api:
        max_retries: 3
        keys:
            preview: ''    # test preview
            public: ''    # test public
    cache:
        json_dumper:
            use: false
            dump_path: '%kernel.cache_dir%/cms/json'
    demo:
        folder: 'demo'
        key: '%env(STORYBLOK_DEMO_TOKEN)%'
