storyblok:
    pages:
        directory:
            - 'pages/'
        base_route: '/storyblok'
    assets:
        downloader:
            use: false
            local_storage: '%shopware.filesystem.public.config.root%/cms-pictures/'
            public_path: '/cms-pictures/'
    api:
        max_retries: 3
        keys:
            preview: ''    # test preview
            public: ''    # test public
    cache:
        json_dumper:
            use: false
            dump_path: '%kernel.cache_dir%/cms/json'
